name: Release

on:
    push:
        tags:
            - "v*"
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        name: Build ${{matrix.target}}
        runs-on: ${{matrix.os}}
        strategy:
            fail-fast: true
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      artifact_name: loghaven
                      asset_name: loghaven-linux-x86_64
                    - os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_name: loghaven
                      asset_name: loghaven-macos-x86_64
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      artifact_name: loghaven
                      asset_name: loghaven-macos-arm64
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_name: loghaven.exe
                      asset_name: loghaven-windows-x86_64.exe
        steps:
            - uses: actions/checkout@v4

            - uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{matrix.target}}
            - name: Build
              run: cargo build --release --target ${{matrix.target}}

            - name: Rename Binary
              shell: bash
              run: |
                  mkdir -p dist
                  cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} dist/${{matrix.asset_name}}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.asset_name}}
                  path: dist/${{matrix.asset_name}}

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'ref/tags')
              with:
                  files: dist/${{matrix.asset_name}}
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
